version: '3'
services: 
  webserver: 
    image: nginx:latest
    ports:
      - "9001:80" 
    volumes:
      - nginx-data:/app-data 
    networks:
      - qtree-network
  dbserver: 
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5000:5432" 
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - qtree-network
networks:
  qtree-network: 
   driver: bridge 
volumes:
  pg-data: 
  nginx-data: 