---
- name: Install nginx in ubuntu
  hosts: ubuntu
  become: yes
  vars: #input
    software_package_list:
      - nginx
      - default-jdk
      - python3.11
      - apache2
      - mysql-server
  tasks:
    - name: Add deadsnakes PPA repository
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
    - name: install softwares
      apt:
        name: "{{ item }}" #ref name mentioned in vars
        state: present
        update_cache: yes
      loop: "{{ software_package_list }}" #iterate