---
- name: uninstall apache
  hosts: all
  become: yes
  tasks:
    - name: stop apache service
      service:
        name: apache2
        state: stopped  
      when: ansible_distribution == 'Ubuntu' 
    - name: uninstall apache in ubuntu
      apt:
        name: apache2
        state: absent
      when: ansible_distribution == 'Ubuntu'
    