---
- name: create file in remote
  hosts: all
  become: yes
  tasks:
    - name: Create ansible user
      user:
       name: umesh
       password: "{{ 'qtree@123' | password_hash('sha512') }}"      
      